apiVersion: v1
kind: Namespace
metadata:
  name: fraud-inference
  labels:
    purpose: ml-inference
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fraud-inference-sa
  namespace: fraud-inference
  annotations:
    # Filled in from `terraform output aks_workload_identity_client_id`
    azure.workload.identity/client-id: "<WORKLOAD_IDENTITY_CLIENT_ID>"
  labels:
    azure.workload.identity/use: "true"
