// Shared domain types for the platform. These mirror the real artifacts
// generated by the Python pipeline (reports_m2/ .. reports_m5/) rather than
// being invented for the UI — see src/data/real-facts.ts for the values.

export type VerificationStatus =
  | "verified"
  | "locally_tested"
  | "unit_tested"
  | "dry_run"
  | "designed_not_deployed"
  | "target_state"
  | "partial"
  | "not_verified"
  | "future_work";

export type HealthState = "healthy" | "warning" | "critical" | "unknown";

export interface ValidationCheck {
  id: string;
  name: string;
  description: string;
  severity: "critical" | "warning";
  status: "pass" | "fail";
  evidence: string;
}

export interface FeatureFunnelStage {
  stage: string;
  count: number;
  description: string;
}

export interface ModelResult {
  id: string;
  name: string;
  isWinner: boolean;
  cvPrAucMean: number;
  cvPrAucStd: number;
  holdoutPrAuc: number;
  holdoutRocAuc: number;
  holdoutF1: number;
  holdoutPrecision: number;
  holdoutRecall: number;
  holdoutAccuracy: number;
  decisionThreshold: number;
  trainingTimeSec: number;
  bestParams: string;
}

export interface ConfusionMatrix {
  truePositive: number;
  trueNegative: number;
  falsePositive: number;
  falseNegative: number;
}

export interface DpMetricRow {
  metric: string;
  normal: number;
  dp: number;
  delta: number;
}

export interface FairnessMetric {
  attribute: string;
  group: string;
  referenceGroup: string;
  nGroup: number;
  nReference: number;
  spd: number;
  spdCi: [number, number];
  spdSignificant: boolean;
  dir: number;
  dirCi: [number, number];
  dirSignificant: boolean;
  eod: number;
  eodCi: [number, number];
  eodSignificant: boolean;
  aod: number;
  aodCi: [number, number];
  aodSignificant: boolean;
}

export interface ThreatRow {
  id: string;
  category: "Spoofing" | "Tampering" | "Repudiation" | "Information Disclosure" | "Denial of Service" | "Elevation of Privilege";
  asset: string;
  attackVector: string;
  existingControl: string;
  residualRisk: "Low" | "Medium" | "High";
  status: VerificationStatus;
}

export interface ComplianceControl {
  id: string;
  framework: "GDPR" | "HIPAA" | "ISO 27001";
  control: string;
  status: "implemented" | "partial" | "not_implemented";
  evidence: string;
  gap?: string;
}

export interface DriftFeatureRow {
  feature: string;
  psi: number;
  status: HealthState;
  driftScore: number;
}

export interface AuditEvent {
  id: string;
  timestamp: string;
  action: string;
  actor: string;
  sha256: string;
  immutable: boolean;
}

export interface MlflowRun {
  id: string;
  runName: string;
  model: string;
  status: "FINISHED" | "FAILED" | "RUNNING";
  prAuc: number;
  rocAuc: number;
  startedAt: string;
  durationSec: number;
}

export interface CiPipelineStage {
  id: string;
  name: string;
  status: "success" | "failed" | "skipped" | "running";
  durationSec: number;
  detail: string;
}

export interface CiRun {
  id: string;
  branch: string;
  commitSha: string;
  commitMessage: string;
  triggeredBy: string;
  status: "success" | "failed" | "running";
  startedAt: string;
  stages: CiPipelineStage[];
}

export interface TerraformResource {
  module: string;
  logicalName: string;
  resourceType: string;
  securityNote: string;
}

export interface K8sResource {
  kind: string;
  name: string;
  purpose: string;
}

export interface ActivityItem {
  id: string;
  title: string;
  description: string;
  timestamp: string;
  status: HealthState;
  module: string;
}

export interface PredictionRequestPreview {
  TransactionAmt: number;
  ProductCD: string;
  card4: string;
  card6: string;
  DeviceType: string;
}

export interface PredictionResponsePreview {
  is_fraud: boolean;
  fraud_probability: number;
  model_version: string;
  request_id: string;
}
